### ISSUE TITLE
Getting an addMarkers error

### ISSUE THREAD

**Issue by elliottmorris** [bhaskarvk/tilegramsR#2] opened 2016-10-18 22:30 UTC
Error in derivePoints(data, lng, lat, missing(lng), missing(lat), "addMarkers") : 
  addMarkers requires non-NULL longitude/latitude values

**Comment by bhaskarvk** [comment] 2016-10-18 22:32
Duplicate of #1.
I merged the fix in rstudio/leaflet last night, please rebuild `devtools::install_github('rstudio/leaflet')`.

**Closed as completed by bhaskarvk** 2016-10-18 22:32 UTC
Labels: duplicate

**Comment by elliottmorris** [comment] 2016-10-18 22:34
Thanks

**Comment by elliottmorris** [comment] 2016-10-18 22:42
Another quick question. What package is "%<>%" found in?

**Comment by bhaskarvk** [comment] 2016-10-18 22:43
magritter, which I think is loaded automatically by dplyr or purrr

**Comment by elliottmorris** [comment] 2016-10-18 22:51
Guess I should have updated R first....woops

Thanks again
